//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerOn.Logging
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogException
    {
        public int Id { get; set; }
        public int LogEntryId { get; set; }
        public int Level { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public string Source { get; set; }
        public string TargetSite { get; set; }
        public string StackTrace { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual LogEntry LogEntry { get; set; }
    }
}
