//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerOn.Logging
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntry
    {
        public LogEntry()
        {
            this.Exceptions = new HashSet<LogException>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string LoggerName { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Message { get; set; }
        public string Thread { get; set; }
        public string Level { get; set; }
        public string Host { get; set; }
    
        public virtual ICollection<LogException> Exceptions { get; set; }
        public virtual RequestInfo RequestInfo { get; set; }
    }
}
