//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerOn.Logging
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoggingEF : DbContext
    {
        public LoggingEF()
            : base("name=LoggingEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LogException> LogExceptions { get; set; }
        public DbSet<LogEntry> LogEntries { get; set; }
        public DbSet<RequestInfo> RequestInfoes { get; set; }
    }
}
