//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerOn.Logging
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestInfo
    {
        public RequestInfo()
        {
            this.LogEntries = new HashSet<LogEntry>();
        }
    
        public int Id { get; set; }
        public string Referer { get; set; }
        public string Url { get; set; }
        public string QueryString { get; set; }
        public string Host { get; set; }
        public string UserAgent { get; set; }
        public string RemoteAddress { get; set; }
        public string ScriptName { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Method { get; set; }
    
        public virtual ICollection<LogEntry> LogEntries { get; set; }
    }
}
